// front-reactjs/src/components/Home.js
import React, { useState, useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../App.css';
import Header from './Header'
import { Tasks } from './Tasks'
import CreateTask from './CreateTask'
import { getAllTasks, deleteTask, fetchSettings } from '../services/TaskService'

function Home() {

  const [tasks, setTasks] = useState([])
  const [numberOfTasks, setNumberOfTasks] = useState([])
  const [isTaskEdited, setTaskEdited] = useState(false)

  useEffect(() => {
    getAllTasks().then(tasks => {
        console.log(tasks)
        setTasks(tasks)
      });
  }, [numberOfTasks, isTaskEdited])


  function delTask(taskId) {
      deleteTask(taskId).then(response => {
        console.log(response)
        setNumberOfTasks(numberOfTasks - 1)
      });
  }

  function taskCreated() {
    setNumberOfTasks(numberOfTasks + 1)
  }

  function taskEdited(res) {
     setTaskEdited(res)
  }
    
  return (
    <div className="App">
      <Header></Header>
      <div className="container mrgnbtm">
        <div className="row">
          <div className="col-md-12">
              <CreateTask taskCreated={taskCreated}></CreateTask>
          </div>
        </div>
      </div>
      <div className="container mrgnbtm">
        <Tasks tasks={tasks} deleteTask={delTask} taskEdited={taskEdited}></Tasks>
     </div> 
  </div>
  );
}

export default Home;

// front-vuejs/src/components/Home.vue
<template>
    <div id="app" class="App">
        <Header></Header>
        <div class="container mrgnbtm">
          <div class="row">
            <div class="col-md-12">
              <CreateTask @createTask="taskCreate($event)"></CreateTask>
            </div>
          </div>
        </div>
        <div class="row mrgnbtm">
          <Tasks v-if="tasks.length > 0" :tasks="tasks" @deleteTask="taskDelete($event)" @editTask='taskEdit($event)'></Tasks>
        </div>
      </div>
  </template>
  
  <script>
  import 'bootstrap/dist/css/bootstrap.css'
  import 'bootstrap-vue/dist/bootstrap-vue.css'
  
  import Header from './Header.vue'
  import CreateTask from './CreateTask.vue'
  import Tasks from './Tasks.vue'
  
  import { getAllTasks, createTask, deleteTask, editTask } from '../services/TaskService'
  
  console.log('Home')
  
  export default {
    name: 'App',
    components: {
      Header,
      CreateTask,
      Tasks
    },
    data() {
        return {
            tasks: [],
            settings: false
        }
    },
    methods: {
      taskCreate(data) {
        console.log('data:::', data)
        createTask(data).then(response => {
          console.log(response)
          this.getAllTasks();      
        });
      },
      getAllTasks() {
        getAllTasks().then(response => {
          console.log(response)
          this.tasks = response
        })
      },
      taskDelete(taskId) {
         deleteTask(taskId).then(response => {
          console.log(response)
          this.getAllTasks();
        });
      },
      taskEdit(task) {
        editTask(task).then(res => {
          console.log(res);
          this.getAllTasks();
        })
      }
    },
    mounted () {
      this.getAllTasks();
    }
  }
  </script>
  
  <style>
    @import '../assets/styles/global.css'; 
  </style>
